name: Pipeline CI/CD

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Permissão
        run: chmod +x gradlew

      - name: Build
        run: ./gradlew build

      - name: Testes
        run: ./gradlew test

      - name: Gerar JAR
        run: ./gradlew bootJar

      - name: Upload do JAR
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: build/libs/*.jar
